---
# This is a service to expose the liveness side car
apiVersion: v1
kind: Service
metadata:
  name: csi-liveness-cephfsplugin-provisioner
  labels:
    app: csi-liveness
spec:
  ports:
    - name: csi-http-metrics
      port: 8080
      protocol: TCP
      targetPort: 9081
  selector:
    contains: csi-cephfsplugin-metrics
