pull_request_rules:
  # automerge backports if CI successfully ran
  - name: automerge backport release-1.1
    conditions:
      - author=mergify[bot]
      - base=release-1.1
      - label!=no-not-merge
      - 'status-success=DCO'
      - 'status-success=continuous-integration/jenkins/pr-head'
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: smart
      dismiss_reviews: {}
      delete_head_branch: {}
# Trigger backport PRs based on label
  - actions:
      backport:
        branches:
        - release-1.1
    conditions:
      - label=backport-release-1.1
    name: backport release-1.1